name: Yggdrasil deployment

on:
  push:
    branches: [ "senpai", "kojirou" ]

permissions:
  pull-requests: write
  contents: write


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install
      - run: pm2 deploy yggdrasil.config.cjs qvssprod
        if: github.ref_name == 'senpai'
      - run: pm2 deploy yggdrasil.config.cjs qvssdev
        if: github.ref_name == 'kojirou'
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes deployed to cirno
            Branch ${{ github.ref_name }}